version: 1
disable_existing_loggers: False
formatters:
  full:
    format: '%(pathname)s : %(lineno)d : %(levelname)s : %(message)s'
  simple:
    format: '%(levelname)s | - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

loggers:
  FlaskFatLog:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
    handlers: [console]